name: sedat
description: A secured database for Hapnium platforms.

publish_to: none

version: 0.2.9
homepage: https://github.com/Hapnium/flutter/tree/main/sedat
repository: https://github.com/Hapnium/flutter/tree/main/sedat

environment:
  sdk: ^3.0.0

dependencies:
  hive_ce_flutter: ^2.3.3
  meta: ^1.17.0

  tracing:
    path: ../tracing
  hapnium:
    path: ../hapnium

dev_dependencies:
  hive_ce_generator: ^1.11.0
  test: ^1.28.0
  lints: ^6.0.0
