name: link_preview
description: A Flutter plugin that is used to display links in a nice ui

publish_to: none

version: 0.0.6
homepage: https://github.com/Hapnium/flutter/tree/main/link_preview
repository: https://github.com/Hapnium/flutter/tree/main/link_preview

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.6
  http: '>=0.13.6 <2.0.0'
  linkify: ^5.0.0
  xml: ^6.6.1
  url_launcher: ^6.3.2
  meta: ^1.17.0
  tracing:
    path: ../tracing

dev_dependencies:
  lints: ^6.0.0