name: tracing
description: "A comprehensive logging library for Flutter applications."

publish_to: none

version: 0.1.5
homepage: https://github.com/Hapnium/flutter/tree/main/tracing
repository: https://github.com/Hapnium/flutter/tree/main/tracing

environment:
  sdk: ^3.0.0

dev_dependencies:
  lints: ^6.0.0