name: device
description: >
  A platform-aware utility for Flutter and Dart. Detect OS, device type, IP, and environment 
  configuration from a single unified interface. Perfect for multi-platform apps.

publish_to: none

version: 0.2.6
homepage: https://github.com/Hapnium/flutter/tree/main/device
repository: https://github.com/Hapnium/flutter/tree/main/device

environment:
  sdk: ^3.0.0

dependencies:
  device_info_plus: ^11.5.0
  meta: ^1.17.0
  universal_io: ^2.3.1

  tracing:
    path: ../tracing
  hapnium:
    path: ../hapnium

dev_dependencies:
  lints: ^6.0.0