name: hapnium
description: A starting point for Dart libraries or applications.

publish_to: none

version: 0.1.3
homepage: https://github.com/Hapnium/flutter/tree/main/hapnium
repository: https://github.com/Hapnium/flutter/tree/main/hapnium

environment:
  sdk: ^3.7.0

dependencies:
  meta: ^1.17.0

dev_dependencies:
  test: ^1.29.0
  lints: ^6.0.0