name: zap
description: "HTTP and Socket client handling requests with error and session management for Hapnium platforms."

publish_to: none

version: 0.3.4
homepage: https://github.com/Hapnium/flutter/tree/main/zap
repository: https://github.com/Hapnium/flutter/tree/main/zap

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0

  tracing:
    path: ../tracing